server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    # refer https://github.com/go-sql-driver/mysql#dsn-data-source-name for details
    source: "root:root@tcp(127.0.0.1:3306)/wallet_local?charset=utf8mb4&parseTime=True&loc=Local"
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
    db: 0
logger:
  output_dir:
  output_filename:
  level: debug
